Analysis of our NRE v2 extractor's extractions on the astrophysics data set (36,596 extractions).

This notebook aims to show how NREs can be used to extract facts for multiple entities + relation combinations simultaneously.

In [1]:
import numpy as np
import pandas as pd
import unicodedata

In [2]:
# Read data
columns = ["sentence", "arg1", "verb", "relation", "arg2", "value_1", "unit_1", "value_2", "unit_2", \
           "q_measure_1", "quantulum_v1", "quantulum_u1", "q_measure_2", "quantulum_v2", "quantulum_u2", "arg1_f", "rel_f"]
# _f in the name indicates filtered to remove stopwords

df = pd.read_csv('astro_NewExtractions.csv', names = columns)
len(df)

36596

In [3]:
# Apply filters
df['value_1'] = pd.to_numeric(df['value_1'], errors='coerce')
df['value_2'] = pd.to_numeric(df['value_2'], errors='coerce')
df2 = df[df.value_1.notna() & df.arg1_f.notna()].reset_index(drop=True)
len(df2)

25872

In [4]:
# Standardize common units
df2.loc[df2['unit_1'] == 'percent', 'unit_1'] = '%'
df2.loc[df2['quantulum_u1'] == 'kilometre', 'unit_1'] = 'kilometers'

In [18]:
gdf1.count()

min      432
max      432
count    432
dtype: int64

In [12]:
# Group data on arg1, relation, and unit
# Count > 10
gdf1 = df2.groupby(["arg1_f","rel_f","unit_1"])['quantulum_v1'].agg(["min","max","count"]).sort_values("count", ascending=False).query("count > 1")
gdf1[gdf1['min'] != gdf1['max']]

                                                                                                   min  \
arg1_f                                 rel_f                        unit_1
orbit                                  inclination                  °                          0.00000
collaborative asteroid lightcurve link diameter                     kilometers                 0.90000
lightcurve analysis                    brightness variation         magnitude                  0.05000
                                       rotation period              hours                      2.42870
                                       brightness amplitude         magnitude                  0.05000
                                       - defined rotation period    hours                      2.59990
s - type asteroid                      rotation period              hours                      2.60000
asteroid                               diameter                     kilometers                 1.10000
analysis                               rotation period              hours                      2.92270
                                       brightness amplitude         magnitude                  0.02000
star                                   sun                          times mass                 0.45000
photometric observations               period                       hours                      2.98000
                                                                    ± 0.002 hours              5.62800
carbonaceous c - type asteroid         rotation period              hours                      5.70000
collaborative asteroid lightcurve link larger diameter              kilometers                 5.70000
japanese akari satellite               measures                     kilometers                 2.38500
photometric observations               period                       ± 0.001 hours              6.97700
x - type asteroid                      rotation period              hours                      5.50000
petr pravecs                           diameter                     kilometers                 3.35100
photometric observations               amplitude                    magnitude                  0.10000
lightcurve analysis                    consolidated rotation period hours                      3.49160
stony s - type asteroid                rotation period              hours                      3.40000
dark d - type asteroid                 rotation period              hours                      6.60000
asteroid                               distance                     days                     945.00000
                                       computed lyapunov time       years                      1.00000
photometric observations               brightness variation         ± 0.01                     0.05000
asteroid                               distance                     years                      3.00000
europe                                 sizes                        mm                        10.00000
photometric observations               brightness variation         ±                          0.02000
light - curve analysis                 brightness variation         magnitude                  0.11000
...                                                                                                ...
lightcurves                            rotation period              hours                      6.39850
lightcurve analysis                    low brightness variation     magnitude                  0.09000
population                             10.9 %                       %                          7.70000
lightcurve analysis                    period                       hours                      5.41155
primary                                mass                         %                         45.00000
light curve analysis                   brightness variation         magnitude                  0.05000
                                       - defined rotation period    hours                      5.61500
radial velocity studies                pulsations                   minutes                   30.40000
refined period                         amplitude                    magnitude                  0.12000
population                             10.9 %                       age                       18.00000
large dynamic range                    electrons                    kev                       40.00000
recent estimates                       distance                     pc                       159.00000
lightcurves                            brightness variation         magnitude                  0.36500
12.13 hours                            period                       hours                      6.67000
129xe                                  abundance                    %                         21.00000
lightcurve analysis                    average rotation period      hours                     23.20000
                                       defined rotation period      hours                      4.66010
previous measurements                  period                       hours                      6.34950
refined lightcurve                     amplitude                    magnitude                  0.14000
lightning rods                         intervals                    m                          6.10000
region                                 earth                        approximately  parsecs  1400.00000
luhman                                 triple alpha centauri system ly                         4.37000
journal                                category " astronomy         journals                  54.00000
quasar                                 distances                    kpc                        3.00000
lightcurve                             similar period               hours                      7.50000
refined lightcurve                     period                       hours                      7.55400
χ2 statistic                           uncertainty                  %                          1.10000
dark carbonaceous c - type asteroid    rotation period              hours                     11.20000
yz ceti                                mass                         %                         13.00000
direct sunlight                        total insolation             / m2                    1050.00000

                                                                                                 max  \
arg1_f                                 rel_f                        unit_1
orbit                                  inclination                  °                         79.500
collaborative asteroid lightcurve link diameter                     kilometers               216.100
lightcurve analysis                    brightness variation         magnitude                 25.155
                                       rotation period              hours                    488.063
                                       brightness amplitude         magnitude                  1.000
                                       - defined rotation period    hours                     85.000
s - type asteroid                      rotation period              hours                     16.190
asteroid                               diameter                     kilometers               317.000
analysis                               rotation period              hours                     93.000
                                       brightness amplitude         magnitude                  1.300
star                                   sun                          times mass                 6.700
photometric observations               period                       hours                     23.990
                                                                    ± 0.002 hours             37.394
carbonaceous c - type asteroid         rotation period              hours                     24.980
collaborative asteroid lightcurve link larger diameter              kilometers                44.220
japanese akari satellite               measures                     kilometers               172.600
photometric observations               period                       ± 0.001 hours             31.900
x - type asteroid                      rotation period              hours                     23.500
petr pravecs                           diameter                     kilometers                84.610
photometric observations               amplitude                    magnitude                  0.450
lightcurve analysis                    consolidated rotation period hours                     64.600
stony s - type asteroid                rotation period              hours                     97.400
dark d - type asteroid                 rotation period              hours                     20.000
asteroid                               distance                     days                    4326.000
                                       computed lyapunov time       years                      3.000
photometric observations               brightness variation         ± 0.01                     0.280
asteroid                               distance                     years                     11.000
europe                                 sizes                        mm                        24.000
photometric observations               brightness variation         ±                          0.280
light - curve analysis                 brightness variation         magnitude                  0.290
...                                                                                              ...
lightcurves                            rotation period              hours                     13.125
lightcurve analysis                    low brightness variation     magnitude                  0.110
population                             10.9 %                       %                         21.400
lightcurve analysis                    period                       hours                     16.000
primary                                mass                         %                         52.000
light curve analysis                   brightness variation         magnitude                  0.390
                                       - defined rotation period    hours                      7.830
radial velocity studies                pulsations                   minutes                   36.900
refined period                         amplitude                    magnitude                  0.160
population                             10.9 %                       age                       65.000
large dynamic range                    electrons                    kev                      350.000
recent estimates                       distance                     pc                       440.000
lightcurves                            brightness variation         magnitude                  0.600
12.13 hours                            period                       hours                     10.600
129xe                                  abundance                    %                         26.000
lightcurve analysis                    average rotation period      hours                     46.300
                                       defined rotation period      hours                     11.600
previous measurements                  period                       hours                     14.685
refined lightcurve                     amplitude                    magnitude                  0.160
lightning rods                         intervals                    m                          7.600
region                                 earth                        approximately  parsecs  1600.000
luhman                                 triple alpha centauri system ly                         7.780
journal                                category " astronomy         journals                  61.000
quasar                                 distances                    kpc                        6.000
lightcurve                             similar period               hours                      8.790
refined lightcurve                     period                       hours                     14.893
χ2 statistic                           uncertainty                  %                          2.700
dark carbonaceous c - type asteroid    rotation period              hours                     14.100
yz ceti                                mass                         %                         17.000
direct sunlight                        total insolation             / m2                    1120.000

                                                                                            count
arg1_f                                 rel_f                        unit_1
orbit                                  inclination                  °                         623
collaborative asteroid lightcurve link diameter                     kilometers                469
lightcurve analysis                    brightness variation         magnitude                 119
                                       rotation period              hours                     109
                                       brightness amplitude         magnitude                  81
                                       - defined rotation period    hours                      64
s - type asteroid                      rotation period              hours                      29
asteroid                               diameter                     kilometers                 23
analysis                               rotation period              hours                      21
                                       brightness amplitude         magnitude                  20
star                                   sun                          times mass                 20
photometric observations               period                       hours                      18
                                                                    ± 0.002 hours              14
carbonaceous c - type asteroid         rotation period              hours                      14
collaborative asteroid lightcurve link larger diameter              kilometers                 13
japanese akari satellite               measures                     kilometers                 12
photometric observations               period                       ± 0.001 hours              12
x - type asteroid                      rotation period              hours                      11
petr pravecs                           diameter                     kilometers                 10
photometric observations               amplitude                    magnitude                  10
lightcurve analysis                    consolidated rotation period hours                      10
stony s - type asteroid                rotation period              hours                      10
dark d - type asteroid                 rotation period              hours                       9
asteroid                               distance                     days                        9
                                       computed lyapunov time       years                       9
photometric observations               brightness variation         ± 0.01                      9
asteroid                               distance                     years                       8
europe                                 sizes                        mm                          8
photometric observations               brightness variation         ±                           8
light - curve analysis                 brightness variation         magnitude                   7
...                                                                                           ...
lightcurves                            rotation period              hours                       2
lightcurve analysis                    low brightness variation     magnitude                   2
population                             10.9 %                       %                           2
lightcurve analysis                    period                       hours                       2
primary                                mass                         %                           2
light curve analysis                   brightness variation         magnitude                   2
                                       - defined rotation period    hours                       2
radial velocity studies                pulsations                   minutes                     2
refined period                         amplitude                    magnitude                   2
population                             10.9 %                       age                         2
large dynamic range                    electrons                    kev                         2
recent estimates                       distance                     pc                          2
lightcurves                            brightness variation         magnitude                   2
12.13 hours                            period                       hours                       2
129xe                                  abundance                    %                           2
lightcurve analysis                    average rotation period      hours                       2
                                       defined rotation period      hours                       2
previous measurements                  period                       hours                       2
refined lightcurve                     amplitude                    magnitude                   2
lightning rods                         intervals                    m                           2
region                                 earth                        approximately  parsecs      2
luhman                                 triple alpha centauri system ly                          2
journal                                category " astronomy         journals                    2
quasar                                 distances                    kpc                         2
lightcurve                             similar period               hours                       2
refined lightcurve                     period                       hours                       2
χ2 statistic                           uncertainty                  %                           2
dark carbonaceous c - type asteroid    rotation period              hours                       2
yz ceti                                mass                         %                           2
direct sunlight                        total insolation             / m2                        2

[338 rows x 3 columns]

In [6]:
# ASTEROID ROTATION PERIODS
# COUNT > 10
gdf2 = df2[df2.arg1.str.contains('asteroid') & df2.relation.str.contains('rotation period')]
gdf2.groupby(["arg1_f","unit_1"])['quantulum_v1'].agg(["min","max","count"]).query("count > 10").sort_values("count", ascending=False)

                                       min    max  count
arg1_f                         unit_1
s - type asteroid              hours   2.5  130.0     39
carbonaceous c - type asteroid hours   5.0  236.6     21
x - type asteroid              hours   3.4   23.5     16
stony s - type asteroid        hours   3.0   97.4     14

In [7]:
# COUNT > 2, Showing filtered relation phrase
gdf2.groupby(["arg1_f", "rel_f","unit_1"])['quantulum_v1'].agg(["min","max","count"]).query("count > 2").sort_values("count", ascending=False)

,,,min,max,count
arg1_f,rel_f,unit_1,,,
s - type asteroid,rotation period,hours,2.60,16.19,29
carbonaceous c - type asteroid,rotation period,hours,5.70,24.98,14
x - type asteroid,rotation period,hours,5.50,23.50,11
stony s - type asteroid,rotation period,hours,3.40,97.40,10
dark d - type asteroid,rotation period,hours,6.60,20.00,9
asteroid,rotation period,hours,5.10,12.05,4
c - type asteroid,rotation period,hours,8.00,19.80,4
d - type asteroid,rotation period,hours,8.96,22.70,4
dark c - type asteroid,rotation period,hours,11.68,16.00,4
primitive p - type asteroid,rotation period,hours,11.00,17.10,4
s - type asteroid,short rotation period,hours,2.50,3.30,4
elongated s - type asteroid,rotation period,hours,6.90,12.30,3
v - type asteroid,rotation period,hours,3.84,15.60,3
x - type asteroid,short rotation period,hours,3.40,5.80,3

In [8]:
# ASTEROID DIAMETERS
# COUNT > 2
gdf3 = df2[df2.arg1.str.contains('asteroid') & df2.relation.str.contains('diameter')]
gdf3.groupby(["arg1_f", "rel_f","unit_1"])['quantulum_v1'].agg(["min","max","count"]).query("count > 2").sort_values("count", ascending=False)

                                                                     min  \
arg1_f                                 rel_f            unit_1
collaborative asteroid lightcurve link diameter         kilometers  0.90
asteroid                               diameter         kilometers  1.10
collaborative asteroid lightcurve link larger diameter  kilometers  5.70
                                       smaller diameter kilometers  2.19

                                                                       max  \
arg1_f                                 rel_f            unit_1
collaborative asteroid lightcurve link diameter         kilometers  216.10
asteroid                               diameter         kilometers  317.00
collaborative asteroid lightcurve link larger diameter  kilometers   44.22
                                       smaller diameter kilometers   56.00

                                                                    count
arg1_f                                 rel_f            unit_1
collaborative asteroid lightcurve link diameter         kilometers    469
asteroid                               diameter         kilometers     23
collaborative asteroid lightcurve link larger diameter  kilometers     13
                                       smaller diameter kilometers      5

In [9]:
# D-TYPE ASTEROID
# COUNT > 10
gdf4 = df2[df2.arg1.str.contains('d[- ]+type +asteroid')]
gdf4.groupby(["rel_f","unit_1"])['quantulum_v1'].agg(["min","max","count"]).query("count > 10").sort_values("count", ascending=False)

                        min   max  count
rel_f           unit_1
rotation period hours   6.6  22.7     16

In [10]:
# S-TYPE ASTEROID
# COUNT > 2
gdf5 = df2[df2.arg1.str.contains('s[- ]+type +asteroid')]
gdf5.groupby(["rel_f","unit_1"])['quantulum_v1'].agg(["min","max","count"]).query("count > 2").sort_values("count", ascending=False)

                               min    max  count
rel_f                 unit_1
rotation period       hours    2.6   97.4     49
long rotation period  hours   24.0  130.0      6
short rotation period hours    2.5    4.9      5

In [11]:
# STAR
# COUNT > 2
gdf6 = df2[df2.arg1.str.contains('star')]
gdf6.groupby(["rel_f","unit_1"])['quantulum_v1'].agg(["min","max","count"]).query("count > 2").sort_values("count", ascending=False)

                                         min       max  count
rel_f          unit_1
sun            times mass               0.45     6.700     22
               times luminosity         0.40   852.000      9
photosphere    times suns luminosity    1.50  1346.000      7
mass           %                        0.10    60.000      6
metallicity    %                       94.00   144.000      5
suns radius    %                       16.00    96.000      4
position angle °                      135.00   155.538      3

#### Conclusions

Produces interesting results, especially in cell 7, with rotation periods of various asteroid types.

However is still limited by extractor performance.